language: rust
sudo: false

before_install:
  - target=x86_64-unknown-linux-musl
  - curl -L https://github.com/mozilla/sccache/releases/download/0.2.7/sccache-0.2.7-$target.tar.gz | tar xzf -
  - export PATH=$PATH:`pwd`/sccache-0.2.7-$target
  - export RUSTC_WRAPPER=sccache

after_script:
  - sccache -s

install:
  - git clone --recursive https://github.com/WebAssembly/wabt.git
  - mkdir wabt/build
  - cd wabt/build
  - cmake .. -DCMAKE_CXX_COMPILER_LAUNCHER=sccache
  - make -j 8
  - cd -
  - export PATH=$PATH:$(pwd)/wabt/build
  - which wasm2wat
  - which wat2wasm

matrix:
  include:
    - name: "test (stable)"
      rust: stable
    - name: "test (beta)"
      rust: beta
    - name: "test (nightly)"
      rust: nightly

    - name: "master doc to gh-pages"
      rust: nightly
      script:
        - cargo doc --no-deps
      deploy:
        provider: script
        script: curl -LsSf https://git.io/fhJ8n | rustc - && (cd target/doc && ../../rust_out)
        skip_cleanup: true
        on:
          branch: master


script:
  - cargo test --all
