[package]
authors = ["Nick Fitzgerald <fitzgen@gmail.com>"]
edition = "2018"
name = "walrus"
version = "0.1.0"

[dependencies]
failure = "0.1.2"
parity-wasm = "0.34.0"
petgraph = "0.4.13"
walrus-derive = { version = "=0.1.0", path = "./walrus-derive" }

[workspace]
members = [
  "./walrus-derive",
  "./walrus-tests",
]
