[package]
authors = ["Nick Fitzgerald <fitzgen@gmail.com>"]
edition = "2018"
name = "walrus-macro"
version = "0.1.0"

[dependencies]
heck = "0.3.0"
proc-macro2 = "0.4.20"
quote = "0.6.8"

[dependencies.syn]
features = ["extra-traits", "full"]
version = "0.15.11"

[lib]
proc_macro = true
